name: moodflow
description: Let your feelings flow - A mood tracking and journaling app.
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.0
  flutter_svg: ^2.0.16
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.1
  gradient_borders: ^1.0.1
  flutter_switch: ^0.3.2
  calendar_date_picker2: ^1.1.8
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  smooth_page_indicator: ^1.2.0+3
  responsive_grid_list: ^1.4.0
  flutter_screenutil: ^5.9.0
  fl_chart: ^0.66.2
  google_fonts: ^6.1.0
  sizer: ^2.0.15
  flutter_launcher_icons: ^0.14.3
  # Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/sos_button.svg
    - assets/images/streak_flame.svg
    - assets/images/background.png
    - assets/images/bottom_bar_home_pressed.svg
    - assets/images/ai_button.svg
    - assets/images/ai_button.png
    - assets/images/img_image.png
    - assets/images/siri_glow.svg
    - assets/images/surprise_me.svg
